#!/bin/bash
update-ipsets enable php_bad
update-ipsets enable blueiv
update-ipsets enable ip2location
update-ipsets enable shunlist
update-ipsets enable xforce
update-ipsets enable coinbl_hosts
update-ipsets enable coinbl_hosts_browser
update-ipsets enable hphosts_ats
update-ipsets enable hphosts_emd
update-ipsets enable hphosts_exp
update-ipsets enable hphosts_fsa
update-ipsets enable hphosts_grm
update-ipsets enable hphosts_hfs
update-ipsets enable hphosts_hjk
update-ipsets enable hphosts_mmt
update-ipsets enable hphosts_pha
update-ipsets enable hphosts_psh
update-ipsets enable hphosts_wrz
update-ipsets enable bi_Php-url-fopen_1_30d
update-ipsets enable bi_apache-defensible_1_30d
update-ipsets enable bi_apache-dokuwiki_1_30d
update-ipsets enable bi_apache-nohome_1_30d
update-ipsets enable bi_apache-overflows_1_30d
update-ipsets enable bi_apache-php-url-fopen_1_30d
update-ipsets enable bi_apache-spamtrap_1_30d
update-ipsets enable bi_apache-w00tw00t_1_30d
update-ipsets enable bi_apache-wordpress_1_30d
update-ipsets enable bi_asterisk-sec_1_30d
update-ipsets enable bi_courierpop3_1_30d
update-ipsets enable bi_cyrusauth_1_30d
update-ipsets enable bi_ddos_1_30d
update-ipsets enable bi_dovecot-pop3_1_30d
update-ipsets enable bi_local-exim_1_30d
update-ipsets enable bi_nginx_1_30d
update-ipsets enable bi_nginxpost_1_30d
update-ipsets enable bi_nginxproxy_1_30d
update-ipsets enable bi_php-cgi_1_30d
update-ipsets enable bi_phpids_1_30d
update-ipsets enable bi_pop3_1_30d
update-ipsets enable bi_proxy_1_30d
update-ipsets enable bi_pureftp_1_30d
update-ipsets enable bi_rfi-attack_1_30d
update-ipsets enable bi_screensharingd_1_30d
update-ipsets enable bi_spamdyke_1_30d
update-ipsets enable bi_sql-injection_1_30d
update-ipsets enable bi_squid_1_30d
update-ipsets enable bi_ssh-auth_1_30d
update-ipsets enable bi_sshddos_1_30d
update-ipsets enable bi_vnc_1_30d
update-ipsets enable bi_w00t_1_30d
update-ipsets enable bi_wp_1_30d
update-ipsets enable bi_xmlrpc_1_30d
update-ipsets enable blueliv_crimeserver_online
update-ipsets enable blueliv_crimeserver_recent
update-ipsets enable blueliv_crimeserver_last
update-ipsets enable sorbs_dul
update-ipsets enable sorbs_anonymizers
update-ipsets enable sorbs_zombie
update-ipsets enable sorbs_smtp
update-ipsets enable sorbs_new_spam
update-ipsets enable sorbs_recent_spam
update-ipsets enable sorbs_web
update-ipsets enable sorbs_escalations
update-ipsets enable sorbs_noserver
update-ipsets enable sorbs_block
update-ipsets enable dronebl_anonymizers
update-ipsets enable dronebl_irc_drones
update-ipsets enable dronebl_worms_bots
update-ipsets enable dronebl_ddos_drones
update-ipsets enable dronebl_compromised
update-ipsets enable dronebl_autorooting_worms
update-ipsets enable dronebl_auto_botnets
update-ipsets enable dronebl_dns_mx_on_irc
update-ipsets enable dronebl_unknown
update-ipsets --enable-all
cron -f
